FROM ubuntu:18.04

# Install GL libraries
RUN apt-get -qq update && apt-get -qq -y install libgl1-mesa-glx

# Install conda
RUN apt-get -qq update && apt-get -qq -y install curl bzip2 \
    && curl -sSL https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -o /tmp/miniconda.sh \
    && bash /tmp/miniconda.sh -bfp /usr/local \
    && rm -rf /tmp/miniconda.sh #\

RUN conda install -y python=3 \
    && conda update -y conda \
    && apt-get -qq -y remove curl bzip2 \
    && apt-get -qq -y autoremove \
    && apt-get autoclean \
    && rm -rf /var/lib/apt/lists/* /var/log/dpkg.log \
    && conda clean --all --yes

# Install git
RUN conda install -y -c anaconda git

# Workdir and input/output/log dir
WORKDIR .
RUN mkdir input output log

# Clone fmippn-oper from Github
#RUN git clone https://github.com/fmidev/fmippn-oper.git && cd fmippn-oper && git checkout -b fix-undetect
RUN git clone --single-branch --branch fix-undetect https://github.com/fmidev/fmippn-oper.git

# Create conda environment
COPY environment_pysteps14.yml fmippn-oper/environment.yml
RUN conda env create -f fmippn-oper/environment.yml -n fmippn

#Cat ppn.py to see that it's the right one
RUN cat fmippn-oper/fmippn/ppn.py

# Disable dask
RUN export OMP_NUM_THREADS=1

# Run
WORKDIR /fmippn-oper/fmippn
ENV domain europe
ENV timestamp 202007071130
ENTRYPOINT conda run -n fmippn python run_ppn.py --config=$domain --timestamp=$timestamp

